### ISSUE TITLE
elynx-markov-0.8.0.0 fails to build with ghc-9.12.2

### ISSUE THREAD

**Issue by juhp** [dschrempf/elynx#6]
Reporting on behalf of Stackage Nightly:

```
       /home/curators/work/unpack-dir/unpacked/elynx-markov-0.8.0.0-0c021d322138fe8ee1cc9539bd7081a1b0f4bae8edba92e8097d0889b99a045b
/src/ELynx/Simulate/MarkovProcessAlongTree.hs:223:37: error: [GHC-25897]                                                            
           • Couldn't match type ‘g’ with ‘IOGen g’
             Expected: MutableGen g IO                            
               Actual: IOGenM g                                   
             ‘g’ is a rigid type variable bound by
               the type signature for:                            
                 parComp :: forall g b.
                            RandomGen g =>
                            Int -> (Int -> IOGenM g -> IO b) -> IOGenM g -> IO [b]                                                  
               at src/ELynx/Simulate/MarkovProcessAlongTree.hs:219:1-82                                                             
           • In the first argument of ‘splitGenM’, namely ‘gen’   
             In the second argument of ‘($)’, namely ‘splitGenM gen’                          
             In a stmt of a 'do' block: rs <- replicateM ncap $ splitGenM gen                                                       
           • Relevant bindings include                                                                                              
               gen :: IOGenM g                                                                                                      
                 (bound at src/ELynx/Simulate/MarkovProcessAlongTree.hs:220:17)                                                     
               fun :: Int -> IOGenM g -> IO b                     
                 (bound at src/ELynx/Simulate/MarkovProcessAlongTree.hs:220:13)    
               parComp :: Int -> (Int -> IOGenM g -> IO b) -> IOGenM g -> IO [b]                                                    
                 (bound at src/ELynx/Simulate/MarkovProcessAlongTree.hs:220:1)                                                      
           |                                                                                                                        
       223 |   rs <- replicateM ncap $ splitGenM gen                                                                                
           |                                     ^^^  
```

**Comment by dschrempf** [comment]
Should be fixed in 0.9.0.0
