### ISSUE TITLE
elynx-tools fails to build with optparse-applicative 0.18

### ISSUE THREAD

**Issue by juhp** [dschrempf/elynx#3]
```
       Building library for elynx-tools-0.7.2.1..                                                                       [240/183885]
       [ 8 of 10] Compiling ELynx.Tools.Options                                                                                     
        
       /var/stackage/work/unpack-dir/unpacked/elynx-tools-0.7.2.1-b456f8629143ad55d733a9c77f7219862ab37a022c0d11b165cd25ed8eb88724/s
rc/ELynx/Tools/Options.hs:227:31: error: [GHC-88464]
           Variable not in scope: 
             text
               :: String
                  -> prettyprinter-1.7.1:Prettyprinter.Internal.Doc AnsiStyle
           |
       227 | fillParagraph = fillSep . map text . words
           |                               ^^^^
        
       /var/stackage/work/unpack-dir/unpacked/elynx-tools-0.7.2.1-b456f8629143ad55d733a9c77f7219862ab37a022c0d11b165cd25ed8eb88724/s
rc/ELynx/Tools/Options.hs:232:5: error: [GHC-88464]
           Variable not in scope: empty :: Doc
           Suggested fixes:
             • Perhaps use ‘mempty’ (imported from Prelude)
             • Perhaps you want to remove ‘empty’ from the explicit hiding list
               in the import of ‘Options.Applicative’
               (src/ELynx/Tools/Options.hs:40:1-41).
           |
       232 |   [ empty,
           |     ^^^^^
:
:
:
```

**Comment by juhp** [comment]
I think using `import Text.PrettyPrint.ANSI.Leijen` can help for now.

**Comment by dschrempf** [comment]
Thank you! Should be fixed in v 0.7.2.2. I will add a PR soon.
